# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turns.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bturns.proto\x12\x05turns\"\x07\n\x05\x65mpty\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\x03\"\x15\n\x06locker\x12\x0b\n\x03num\x18\x01 \x01(\x03\"Y\n\x04turn\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x12\x10\n\x08lock_num\x18\x03 \x01(\x05\x12\x11\n\tinit_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\"\xa4\x02\n\x0b\x66reeLockers\x12\x0f\n\x07locker1\x18\x01 \x01(\x08\x12\x0f\n\x07locker2\x18\x02 \x01(\x08\x12\x0f\n\x07locker3\x18\x03 \x01(\x08\x12\x0f\n\x07locker4\x18\x04 \x01(\x08\x12\x0f\n\x07locker5\x18\x05 \x01(\x08\x12\x0f\n\x07locker6\x18\x06 \x01(\x08\x12\x0f\n\x07locker7\x18\x07 \x01(\x08\x12\x0f\n\x07locker8\x18\x08 \x01(\x08\x12\x0f\n\x07locker9\x18\t \x01(\x08\x12\x10\n\x08locker10\x18\n \x01(\x08\x12\x10\n\x08locker11\x18\x0b \x01(\x08\x12\x10\n\x08locker12\x18\x0c \x01(\x08\x12\x10\n\x08locker13\x18\r \x01(\x08\x12\x10\n\x08locker14\x18\x0e \x01(\x08\x12\x10\n\x08locker15\x18\x0f \x01(\x08\x12\x10\n\x08locker16\x18\x10 \x01(\x08\"\x1a\n\x07success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n\x05\x64\x61tes\x12\x15\n\rinit_datetime\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x02 \x01(\t2\x93\x02\n\x05TURNS\x12\x34\n\x0eGetFreeLockers\x12\x0c.turns.empty\x1a\x12.turns.freeLockers\"\x00\x12\'\n\x0bUserGotTurn\x12\t.turns.id\x1a\x0b.turns.turn\"\x00\x12-\n\rLockerGotTurn\x12\r.turns.locker\x1a\x0b.turns.turn\"\x00\x12\'\n\tStartTurn\x12\x0b.turns.turn\x1a\x0b.turns.turn\"\x00\x12(\n\x07\x45ndTurn\x12\x0b.turns.turn\x1a\x0e.turns.success\"\x00\x12)\n\x08GetTurns\x12\x0c.turns.dates\x1a\x0b.turns.turn\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turns_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_ID']._serialized_start=31
  _globals['_ID']._serialized_end=47
  _globals['_LOCKER']._serialized_start=49
  _globals['_LOCKER']._serialized_end=70
  _globals['_TURN']._serialized_start=72
  _globals['_TURN']._serialized_end=161
  _globals['_FREELOCKERS']._serialized_start=164
  _globals['_FREELOCKERS']._serialized_end=456
  _globals['_SUCCESS']._serialized_start=458
  _globals['_SUCCESS']._serialized_end=484
  _globals['_DATES']._serialized_start=486
  _globals['_DATES']._serialized_end=538
  _globals['_TURNS']._serialized_start=541
  _globals['_TURNS']._serialized_end=816
# @@protoc_insertion_point(module_scope)