# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clocker.proto\x12\x06locker\"\x1a\n\x07success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\x03\"\x16\n\x04\x64oor\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0b\x64oor_closed\x12\x0e\n\x06\x63losed\x18\x01 \x01(\x08\"\x07\n\x05\x65mpty\"+\n\x06outlet\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x11\n\tactivated\x18\x02 \x01(\x08\"*\n\x0b\x63onsumption\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05power\x18\x02 \x01(\x02\"2\n\x04\x63\x61rd\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65tected\x18\x03 \x01(\x08\"0\n\x05sound\x12\n\n\x02on\x18\x01 \x01(\x08\x12\r\n\x05sound\x18\x02 \x01(\x05\x12\x0c\n\x04loop\x18\x03 \x01(\x08\"4\n\x05\x64\x61tes\x12\x15\n\rinit_datetime\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x02 \x01(\t2\xa5\x02\n\x06LOCKER\x12+\n\x08OpenDoor\x12\x0c.locker.door\x1a\x0f.locker.success\"\x00\x12\x33\n\x0cIsDoorClosed\x12\x0c.locker.door\x1a\x13.locker.door_closed\"\x00\x12.\n\tSetOutlet\x12\x0e.locker.outlet\x1a\x0f.locker.success\"\x00\x12\x32\n\x08GetPower\x12\r.locker.dates\x1a\x13.locker.consumption\"\x00\x30\x01\x12&\n\x05GetID\x12\r.locker.empty\x1a\x0c.locker.card\"\x00\x12-\n\tPlaySound\x12\r.locker.sound\x1a\x0f.locker.success\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'locker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUCCESS']._serialized_start=24
  _globals['_SUCCESS']._serialized_end=50
  _globals['_ID']._serialized_start=52
  _globals['_ID']._serialized_end=68
  _globals['_DOOR']._serialized_start=70
  _globals['_DOOR']._serialized_end=92
  _globals['_DOOR_CLOSED']._serialized_start=94
  _globals['_DOOR_CLOSED']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_OUTLET']._serialized_start=134
  _globals['_OUTLET']._serialized_end=177
  _globals['_CONSUMPTION']._serialized_start=179
  _globals['_CONSUMPTION']._serialized_end=221
  _globals['_CARD']._serialized_start=223
  _globals['_CARD']._serialized_end=273
  _globals['_SOUND']._serialized_start=275
  _globals['_SOUND']._serialized_end=323
  _globals['_DATES']._serialized_start=325
  _globals['_DATES']._serialized_end=377
  _globals['_LOCKER']._serialized_start=380
  _globals['_LOCKER']._serialized_end=673
# @@protoc_insertion_point(module_scope)
