# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\x03\"t\n\x08userData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x10\n\x08lastname\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x0f\n\x07profile\x18\x07 \x01(\t\"\x1a\n\x07success\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9c\x02\n\x05USERS\x12\'\n\x07GetUser\x12\t.users.id\x1a\x0f.users.userData\"\x00\x12&\n\x07RegCard\x12\t.users.id\x1a\x0e.users.success\"\x00\x12,\n\x07RegUser\x12\x0f.users.userData\x1a\x0e.users.success\"\x00\x12\x32\n\rChangeProfile\x12\x0f.users.userData\x1a\x0e.users.success\"\x00\x12/\n\nDeleteUser\x12\x0f.users.userData\x1a\x0e.users.success\"\x00\x12/\n\nDeleteCard\x12\x0f.users.userData\x1a\x0e.users.success\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ID']._serialized_start=22
  _globals['_ID']._serialized_end=38
  _globals['_USERDATA']._serialized_start=40
  _globals['_USERDATA']._serialized_end=156
  _globals['_SUCCESS']._serialized_start=158
  _globals['_SUCCESS']._serialized_end=184
  _globals['_USERS']._serialized_start=187
  _globals['_USERS']._serialized_end=471
# @@protoc_insertion_point(module_scope)

